name: Build mGBA ARMv5

on:
  workflow_dispatch:

jobs:
  build-linux-armel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v3

      - name: Build mGBA (armel)
        run: |
          docker run --platform linux/arm/v5 -v $PWD:/ws arm32v5/debian:11 bash /ws/build-armv5.sh

      - name: Prepare go-bin-deb and generate package
        run: |
          wget https://github.com/mh-cbon/go-bin-deb/releases/download/0.0.19/go-bin-deb-amd64.deb
          sudo apt -y install ./go-bin-deb-amd64.deb
          rm go-bin-deb-amd64.deb
          sudo chmod +x armel/mgba
          go-bin-deb generate --file .github/workflows/debmgba.json --wd . --version 0.0.1 --arch armel

      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            armel/mgba
            *.deb

      - name: Upload package to Gemfury
        env:
          GEMFURY_TOKEN: ${{ secrets.GEMFURY_TOKEN }}
        run: |
          for deb in *.deb; do
            curl -F package=@$deb -u "${GEMFURY_TOKEN}:" https://push.fury.io/tunakan0-sketch/
          done
